### ISSUE TITLE
Assignment count mismatch failure on go get

### ISSUE THREAD

**Issue by bprosnitz** [golang/lint#103]
go get github.com/golang/lint/golint
# github.com/golang/lint
../../go/src/github.com/golang/lint/lint.go:1432: assignment count mismatch: 2 = 3

**Comment by zimmski** [comment]
Solution: `go get -u golang.org/x/tools`
Duplicates 99 97 93 92

**Comment by dsymonds** [comment]
This is also mentioned in the "guidelines for contributing" that was prominently displayed when you were filing this issue. Unfortunately I can't change that link text to make it clear that you should read it before filing issues too.

**Comment by bprosnitz** [comment]
Would it be useful to add this to the install instructions?

**Comment by dsymonds** [comment]
I don't know. It's not a problem if it's the first time you're getting the golang.org/x/tools repo (since you'll get the latest version), and I'm loathe to suggest always updating it since you could run into problems in the other direction (other packages depending on some older version). Right now I think people installing this from source just need to know what they're doing somewhat.
