### ISSUE TITLE
NOLINT comment to disable lint locally

### ISSUE THREAD

**Issue by grep0** [golang/lint#114]
Feature request (borrowed from cpplint): add `// NOLINT` comment to mute lint message in a line with such comment.

**Comment by dsymonds** [comment]
Nope, not interested. Please review the README for this repo.

**Comment by gbbr** [comment]
What an awful response @dsymonds. This is a valid and common use case, for example: implementing the methods names of an interface belonging to another package which doesn't respect golint rules. Now, because I am using this package, I can not use `golint`, even though technically the package is golint-correct.

**Comment by ianlancetaylor** [comment]
@gbbr See https://golang.org/issue/38968.

**Comment by gonzispina** [comment]
@dsymonds Not cool
