### ISSUE TITLE
golint cmd not found (please update installation instructions)

### ISSUE THREAD

**Issue by crunchytom** [golang/lint#171]
I eventually found it in my $GOPATH/bin which is of course not in my path, but I could have saved a lot of time if the installation instructions in the readme included this info.

eg, "If the installation succeeds, the golint binary should now be in $GOPATH/bin/golint"

I don't think this is inherently obvious to installers since most people that are installing golint are going to skew toward being new to go and the go ecosystem, and like me will not have $GOPATH/bin in their path.

**Comment by dsymonds** [comment]
It's not really up to golint to teach people how to install and use Go itself. It's also not a tool that true beginners should really be diving into either.

https://golang.org/doc/install describes what happens when you `go install` something.

**Comment by parikshitsm** [comment]
Hello, Probably this thread is quite older one. 
But I found this relevant to my current application error. While making the fabric-sdk directory am getting below errors. Can someone please help to resolve. 

$ mingw32-make
Installing dependencies…
Checking committed files for SPDX-License-Identifier headers …
All files have SPDX-License-Identifier headers
Running linters…
Checking ./pkg/config
C:\Projects\Go\src\github.com\hyperledger\fabric-sdk-go\test\scripts\check_lint.sh: line 22: golint: command not found
Makefile:32: recipe for target ‘lint’ failed
mingw32-make: *** [lint] Error 127

I have golint at my \GOPATH\bin folder. I also added this to system variables, but still golint doesn't work.

**Comment by Rambatino** [comment]
"Installation instructions don't accurately explain how to install and requires inherent knowledge on language features". I don't get how hard it is to explain, in the installation instructions, _what is required to get it working_.

**Comment by micky2be** [comment]
Agreed with people here. I can run `go` command with no problem but getting trouble to execute `golint`.
What is the requirement here? Is there a path missing? The link above does not share in relevant information.

**Comment by andybons** [comment]
Updated `README.md`

**Comment by icambridge** [comment]
> It's not really up to golint to teach people how to install and use Go itself. It's also not a tool that true beginners should really be diving into either.

No, but it is up to golint to teach people how to install golint. If following the installation instructions completely doesn't end up with a functioning golint the installation instructions are wrong. Considering the fix is to state that after installation the binary will be in $GOPATH/bin or even a link to the Go documentation where it states where it will be, this seems to be a rather silly documentation bug to have and refuse to solve. As it stands the documentation for this repository is broken/incomplete. While it's main cause is the Go project itself, the fact this is in the golang organisation makes me believe think that this it is this repositories job to teach people how to use Go enough that they can use this tool and that this is something we should be able to create a quick PR for and solve. The fact it's not for true beginners doesn't remove the fact that I personally have written quite a lot of Go code before but haven't done so in 6+ months and have a new computer so my Go setup is brand new and I need to relearn a lot of the silly one-time-only setup things that Go demands.

**Comment by colinster** [comment]
Agreed. This tool is considered buggy because I had to come here to find the proper documentation.
