### ISSUE TITLE
Are dot imports evil?

### ISSUE THREAD

**Issue by tucnak** [golang/lint#179]
I found a couple of handy use cases where use of dot imports makes lots of sense. Is there a way to mute golint output for these?

**Comment by zimmski** [comment]
This is flagged as a problem because of https://github.com/golang/go/wiki/CodeReviewComments#import-dot which has a good argument to not use it outside of *_test packages. What is your use-case?

golint will properly never have a functionality to disable certain checks but you can always work around this by filtering the output e.g. with `grep --invert-match ...`

**Comment by tucnak** [comment]
I've got a helper library, providing a bunch of helper funcs. It's quite inconvenient to specify lib name each time I refer to some function, dot import saves some pain.

**Comment by dsymonds** [comment]
Helper libraries often turn into junk drawers, especially when their common use cases aren't qualified with a unifying concept but are instead in a `util` package or similar. If it's painful to qualify names from a package with that package's name, perhaps that package needs a rethink.

**Comment by advanderveer** [comment]
A valid reason to use dot imports outside testing is for domain specific languages that use Go. The popular project [Goa](https://goa.design/design/overview/) comes to mind but i'm working on a DSL myself as well. The goals in those cases is always expressiveness and adding the package for every "word" clutters what you're trying to write down.

**Comment by l0k1verloren** [comment]
In my opinion tests are not the only place for dot imports. If I write a data storage library that is applicable to multiple data payload types (such as a binary tree), the payload datatype implementing library has to be liberally spiced with full package prefixes for every overridden function and this gets cumbersome when you choose to instead of use common convention of cryptic return values to shrink the number of methods in a library instead of writing informative, expressive function names to improve readability of consuming applications and library code, it's a lot of boilerplate that is unnecessary because the implementation library is extending the base library, and therefore implicitly does not have namespace conflicts.

At least, the way I write them anyway. So I'll put up with the green squiggles in the import block for now but just wanted to point out that tests are not the only valid place for merging namespaces.

**Comment by gdamore** [comment]
Use case.  A group of related packages, but want to use common error codes between them.  Create an "errors" package containing *only* the constants for the error codes.  This lets me import those constants directly into my packages -- so I can have:

if err == ErrClosed {
}

instead of 

if err = mangos.ErrClosed {
}

When testing against many error values, and using the same constants all around, the extra package keyword in front becomes a significant PITA and hinders readability rather than helping it.

Obviously dot imports are vile when abused, but when carefully utilized they can improve quality rather than reducing it.

**Comment by gdamore** [comment]
And yes, I could define local constants e.g. 

import "mangos/errors"

const (
   ErrClosed = mangos.ErrClosed
)

The problem with this approach is that then ErrClosed becomes part of my exported signature -- NOT what I intended.  Or, I can use a name that is different, "errClosed" say - but this hides the important relationship that this is one of the common error constants I use throughout this family of packages.

Dot imports give me the import, without polluting my *exported* namespace.

**Comment by billyzaelani** [comment]
Another use case. Supposed I create a library that can transpiled Go code into html, I could write:

import . "github.com/x/html" // imaginary lib for linting purposes

func main() {
    HTML(
        Head(
            Title().Content("Go-HTML"),
        ),
        Body().Content("Yay, I write HTML using Go"),
    )
}

**Comment by amineb3n** [comment]
It can be useful when importing common types that are used in multiple related packages. 

I guess, all the files could be put in the same package but then it will either be hundreds of files in one folder or few giant files (each would have all the code of the sub-packages). 

It is convenient to be able to have things like:

--src/
----ns/
------component/
--------encoder/
--------processor/
--------repository/
--------types/types.go // <--- used everywhere in component/...                     

so it is useful when splitting big package into smaller sub-packages without hurting readability.
