### ISSUE TITLE
Incorrectly detects ALL_CAPS warning for numeric names

### ISSUE THREAD

**Issue by eapache** [golang/lint#221]
Specifically any variables named such as `V123_456` will give the warning about using ALL_CAPS and suggest camel-case, which is incorrect. The initial capital is necessary to export the variable and none of the other characters have lower-case alternatives.

**Comment by dsnet** [comment]
May I ask what the original variable or constant name was? `V123_456` doesn't seem like a exported value realistically seen in packages.

**Comment by eapache** [comment]
It's in a client library supporting certain specific versions of the upstream project. We provide exported values for those versions, which users can then pass back in as configuration. So `V0_8`, `V0_9`, `V1_0` and that sort of thing.

https://github.com/Shopify/sarama/blob/9bb4a68d57ff6f623363aa172f0a8297aa289ba7/utils.go#L141-L150

**Comment by andybons** [comment]
From what I can see, the fix for this would be either too specific to this instance, or too complex to cover all cases reliably. I’m afraid this falls into “sometimes there will be false positives” as noted in the README:

> Golint is not perfect, and has both false positives and false negatives. Do not treat its output as a gold standard.

If you can come up with a simple fix that covers most cases, feel free to re-open.
