### ISSUE TITLE
Support for plugin rules

### ISSUE THREAD

**Issue by ggeorgiev** [golang/lint#241]
I have a few core libraries that are used in my company. They came with their own set of good practices. Obviously, none of them belongs to a generic purpose system like this one. It will be nice if I can plug in my own set of checks into the system before I run it.

**Comment by mvdan** [comment]
There are lots of linters out there. Why not simply use separate linters for extra checks?

If there were rules that made sense to add to golint via plugins, they should probably just be added. And if not, they should be in separate linters.

**Comment by ggeorgiev** [comment]
Why having many linters is better over having a single linter with plugins? Sharing the common administrative/operational) part seems appealing to me.

**Comment by dsnet** [comment]
The difficulty of plugins is that we need to define a common API that all the plugins can use. If the API is too narrow, then not very many useful plugins can be written. If the API is too broad, then it becomes too cumbersome to use.

When we step back and think about how lint works, I would argue each lint rule is actually wrappers around the functionality already exposed in the standard library: https://golang.org/pkg/go/

Thus, you are certainly welcome to use those packages to write your own lint program to run alongside the "official" one.

**Comment by mvdan** [comment]
@ggeorgiev on top of what @dsnet said, if you mean code - have a look at x/tools/go/loader. With that, writing a linter is trivial and code duplication across linters is minimal.

**Comment by ggeorgiev** [comment]
My background is from c++ where linting was almost completely impossible for one guy to do, and clang seems to be favoring the plugin architecture - even with LLVM succeeded to make the extra work needed minimal. Anyways I will have to trust you on this.

Before I close the issue, though - as a no issue - I feel like the comment in #242 actually contradicts the comments here. If there is an extra "framework" that needs to be done for one case - the same might be very useful for other cases as well, isn't it?

By the way, I was unable to run the suggested alternative linter https://github.com/mdempsky/unconvert and I never had any issues with yours (thanks for that) - kind of aligning with my concern that many linters - harder to maintain and use.

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
