### ISSUE TITLE
No documentation for confidence values

### ISSUE THREAD

**Issue by jdonboch** [golang/lint#251]
Currently there is no documentation on the effects of raising or lowering the confidence levels. It would be nice to know what is being checked at what confidence levels and the impacts of what would be gained/lost by changing the confidence value.  

Would a PR be accepted if I compiled this in a markdown document or added it to the godocs somewhere?  It would add a contributing requirement that this list would be maintained when checks are added/updated/removed.

**Comment by dsnet** [comment]
I appreciate the offer to create a separate document, but the major downside is that any external document will rot over time and the documented values will drift away from what the lint tool actually does as checks are added/removed and confidence levels are tweaked.

I believe the proper solution may be for the lint tool to print out what type of checks it can do and the associated confidence levels. However, this is a much larger scale change to the lint code-base than we would want to carry out right now. This is further complicated by the fact that a given check sometimes alters it confidence based on a plurality of parameters. How exactly do you document that?

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
