### ISSUE TITLE
Warn when user passes a nil Context

### ISSUE THREAD

**Issue by rakyll** [golang/lint#257]
[context](https://golang.org/pkg/context/) package says,

> Do not pass a nil Context, even if a function permits it. Pass context.TODO if you are unsure about which Context to use.

Yet, Go users seem to think passing nil Contexts is valid behavior and expecting packages to handle the case where context is nil.

In order to be able to communicate the expectation from the user, warn if they pass nil.

**Comment by dsnet** [comment]
Hey @dominikh, how frequent were failures caught by this check?

**Comment by dominikh** [comment]
@dsnet I hadn't checked yet (frequency isn't a primary criterion for staticcheck, and my primary corpus is from pre stdlib context days). 

I can start a run on a newer corpus tonight  and tell you the results tomorrow.

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
