### ISSUE TITLE
can i set some word not lint?

### ISSUE THREAD

**Issue by guotie** [golang/lint#262]
such as Id, etc

**Comment by dsnet** [comment]
Hi, I apologize, but I do not understand this issue report.

**Comment by guotie** [comment]
such as Id , golint will warning it to be ID, I want golint ignore this word.

**Comment by dsnet** [comment]
Trying to whitelist a specific word is too specific of feature to provide, but I can imagine behavior of this sort to be covered by #263.

That being said, the style that the Go community has converged upon is to use "ID" instead of "Id" as a shorthand for the word "identity". I would highly recommend against ignoring this warning.
