### ISSUE TITLE
Invalid docs checking

### ISSUE THREAD

**Issue by kirillDanshin** [golang/lint#265]
As you can see in https://github.com/avelino/awesome-go/pull/1239 golint on goreportcard is happy, but godocs have only `<name> -`. Some other packages have only `<name> ...` comments.

Can we somehow fix this?

**Comment by dsnet** [comment]
I'm not sure what can be done. We can add "<name> -" and "<name> ..." to a list of abuses, but there are a near infinite number of ways people abuse the new rules to still write bad comments.

It seems to me that `lint` did its job such that the author did "<name> -" to silence `lint`. There's nothing the `lint` tool can do when people ignore `lint`'s suggestions.

**Comment by shurcooL** [comment]
I agree, I think golint is behaving as expected, and it should not try to do anything differently. That type of comment is a minimum documentation that silences the warning. People won't do that by accident.

**Comment by kirillDanshin** [comment]
I don't mean that it was accident.
we can create a flag that will disallow " -", " ..." etc.

**Comment by dsnet** [comment]
Suppose we add a flag, how would that help the problem? Would goreportcard then pass in a custom list of common strings used to cheat the check? However, any blacklist chosen can always be cheated again. I don't see any way for this to be solved short of adding machine learning to recognize bad documentation.

I'm going to close this issue. I agree with the spirit of what this issue is trying to solve, but I don't see any technical way for this to be satisfactorily solved inside `lint`.
