### ISSUE TITLE
Make `commonInitialisms` public

### ISSUE THREAD

**Issue by b0o** [golang/lint#272]
This would be useful for cases where code is being generated automatically, e.g. using `go generate ...`. 

I'm generating funcs/types/methods based on a YAML file; one of my type names is "sql" - It needs to be lowercase in my YAML file because some of the generated code is private, and I need to support other type names which are camelCase - I modify the case automatically.

Thus, in order to comply with `golint`, I need to check the first part of each string against the `commonInitialisms` map (currently located at [lint.go:731](https://github.com/golang/lint/blob/master/lint.go#L731)).

At the moment, I need to hardcode a copy of the `commonInitialisms` map and hope that it doesn't change in this repo. :)

**Comment by dsnet** [comment]
Hi. You mention that you would like access to `commonInitialisms` to presumably generate lint-happy Go code. Do you think that perhaps #239 is the root solution for your problem?

**Comment by b0o** [comment]
@dsnet Well, my generator runs the code through GoFmt and produces some pretty decent looking code. The only thing GoLint has ever complained about was the capitalization thing. Not all generated files are going to be human-unreadable.

To answer your question, no, I don't think that #239 is the root solution for my problem - it feels like more of a bandaid.

**Comment by ereOn** [comment]
@b0o You are actually not alone and I have the exact same use case.

I would even go further and ask whether `lintName()` itself can be made public.

My generator happens to "create" CamelCased names from snake_cased ones (from a different language) and it's very difficult, if not impossible to make `golint` happy with those files if we can't access its internal logic for deciding when a name isn't a recommended one.

**Comment by petemoore** [comment]
Indeed, I also needed it for my jsonschema2go library, which generates go types based on json schemas. I ended up [duplicating the initialisms](https://github.com/taskcluster/jsonschema2go/blob/e3150890d3ddaa1105489cce6ebb2206f5a31ad4/text/text.go#L42-L81), but if it was public, I would not have needed to.

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
