### ISSUE TITLE
Constants should be comentable in blocks

### ISSUE THREAD

**Issue by morriswinkler-simple** [golang/lint#274]
I am referring to #208

```
// Mobility is how you move on
type Mobility int

const (
	Lame  Mobility = iota // Immobile motion
	Car                   // Motion by car
	Plane                 // Motion by plane
	Ship                  // Motion by ship
)

const (
	// Immobile motion
	Lame2 Mobility = iota
	// Motion by car
	Car2
	// Motion by plane
	Plane2
	// Motion by ship
	Ship2
)

```

translate perfectly fine into godoc go version go1.7.4 darwin/amd64

##### generated with godoc
<pre>const (
    <span id="Lame">Lame</span>  <a href="#Mobility">Mobility</a> = <a href="/pkg/builtin/#iota">iota</a> <span class="comment">// Immobile motion</span>
    <span id="Car">Car</span>                   <span class="comment">// Motion by car</span>
    <span id="Plane">Plane</span>                 <span class="comment">// Motion by plane</span>
    <span id="Ship">Ship</span>                  <span class="comment">// Motion by ship</span>
)</pre>

<pre>const (
    <span class="comment">// Immobile motion</span>
    <span id="Lame2">Lame2</span> <a href="#Mobility">Mobility</a> = <a href="/pkg/builtin/#iota">iota</a>
    <span class="comment">// Motion by car</span>
    <span id="Car2">Car2</span>
    <span class="comment">// Motion by plane</span>
    <span id="Plane2">Plane2</span>
    <span class="comment">// Motion by ship</span>
    <span id="Ship2">Ship2</span>
)</pre>

**Comment by majimboo** [comment]
This works fine for me on 1.8.1.

**Comment by puellanivis** [comment]
```
// Mobility is how you move on
type Mobility int

// Various kinds of Mobility
const (
	Lame  Mobility = iota
	Car
	Plane
	Ship
)
```

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
