### ISSUE TITLE
Cannot get the package

### ISSUE THREAD

**Issue by ehouarn-perret** [golang/lint#288]
For some reasons some packages cannot be setup with `go get` like golint
It seems to be completely unrelated to the proxy or the firewall.
```
go get -u -t -v github.com/golang/lint/golint
github.com/golang/lint (download)
Fetching https://golang.org/x/tools/go/gcexportdata?go-get=1
https fetch failed: Get https://golang.org/x/tools/go/gcexportdata?go-get=1: dial tcp 172.217.10.241:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
package golang.org/x/tools/go/gcexportdata: unrecognized import path "golang.org/x/tools/go/gcexportdata" (https fetch: Get https://golang.org/x/tools/go/gcexportdata?go-get=1: dial tcp 172.217.10.241:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
```
Same issue happens with guru, go-symbols, gorename, goreturns, golint and gotests.

**Comment by 834449164** [comment]
I also encountered this problem!
C:\Users\Administrator>go get -u github.com/golang/lint/golint
package golang.org/x/tools/go/gcexportdata: unrecognized import path "golang.org/x/tools/go/gcexportdata" (https fetch: Get https://golang.org/x/tools/go/gcexportdata?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by nerd010** [comment]
I also encountered this problem!
how to fix it?

**Comment by zengming00** [comment]
I also encountered this problem!
how to fix it?

**Comment by dsnet** [comment]
I cannot reproduce this issue. Where are you running `go get -u -t -v github.com/golang/lint/golint` from? What operating systems are you using? What versions of Go?

Please don't just say "me too". It's not helpful.

**Comment by 834449164** [comment]
The problem is solved now.
VS Code can download it now, it's maybe a network problem before.

**Comment by CharXu** [comment]
But I have the same problem even if use VS Code to download

**Comment by artificerpi** [comment]
Same problem. go version: `go version go1.6.2 linux/amd64` `Ubuntu 16.04`

I fix it by removing `tools` folder and use `go get` to install the package again，hope it helps.

**Comment by HeChuanXUPT** [comment]
same
go version go1.8.3 windows/amd64
$ go get github.com/golang/lint
package golang.org/x/tools/go/gcexportdata: unrecognized import path "golang.org/x/tools/go/gcexportdata" (https fetch: Get https://golang.org/x/tools/go/gcexportdata?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by littleomz** [comment]
Fixed it by `mkdir -p $GOPATH/src/golang.org/x/` and cd into this __DIR__ :
```
git clone https://github.com/golang/tools.git
```
Then my VS Code install all the packages SUCCEEDED
Hope it's helpful to you

**Comment by ritayzy** [comment]
> 
Fixed it by mkdir -p $GOPATH/src/golang.org/x/ and cd into this DIR :

git clone https://github.com/golang/tools.git
Then my VS Code install all the packages SUCCEEDED
Hope it's helpful to you #

@littleomz Thanks! This solved my problem

**Comment by mojinfu** [comment]
I also encountered this problem!
i have two gopath ,i did  the fix action  as @littleomz said  in each gopath .
but it  still  not work.

**Comment by macoscoder** [comment]
`
mkdir -p $GOPATH/src/golang.org/x
cd $GOPATH/src/golang.org/x
git clone https://github.com/golang/tools.git
git clone https://github.com/golang/lint.git
`
完成以上步骤后，执行
`
go get golang.org/x/lint/golint
`
成功安装golint ，亲测有效

或者打开vscode，让vscode自行安装，应该也能成功

**Comment by linuxjh** [comment]
im using visual studio code and it prompts to install additional packages: go-outline, go-symbols, guru, gorename, goreturns, golint.

because golang.org are blocked here. i download mirror packages: lint, tools from github web pages and set up my workplace. this has the fetch lint problem.

using git clone those mirror packages solves my problem too, thanks.

thereis an article "Why is Golang popular in china"

but do you know golang is blocked in china too. its just too tough!!!

**Comment by stonedreamforest** [comment]
> mkdir -p $GOPATH/src/golang.org/x
```
XXX-Mac:~ XXX$ go get golang.org/x/mobile/cmd/gomobile
package golang.org/x/mobile/cmd/gomobile: unrecognized import path "golang.org/x/mobile/cmd/gomobile" (https fetch: Get https://golang.org/x/mobile/cmd/gomobile?go-get=1: dial tcp 216.58.194.177:443: connect: connection refused)

XXX-Mac:~ XXX$ mkdir -p $GOPATH/src/golang.org/x
mkdir: /src/golang.org/x: Read-only file system
```

**Comment by danihwsr** [comment]
What helped me regarding the failed connection attempts, when trying to install gotools via VSCODE, was to set my corporate proxy in VSCODE's settings.json:

`"http.proxy": "http://proxy-address:proxy-port`
