### ISSUE TITLE
don't require doc comments for MarshalJSON and UnmarshalJSON

### ISSUE THREAD

**Issue by ecc1** [golang/lint#295]
just like String() and other methods for common interfaces, the comment is unlikely to be anything but boilerplate

**Comment by SamWhited** [comment]
A little boilerplate is nice if it lets me know what interface `String()` is satisfying so that I can look up what will use that behavior (it is obvious what `String()` does from the name, it is not obvious what common thing might be using that); personally I think nothing else should be added to this whitelist (I'd go so far as to say that it should be removed).

**Comment by andybons** [comment]
Duping into #322
