### ISSUE TITLE
go-lint could catch possible race conditions

### ISSUE THREAD

**Issue by KernelDeimos** [golang/lint#296]
This is definitely not something trivial - it would be a huge challenge to implement, especially considering this may sometimes be done on purpose. However, it would be extremely awesome of the linter could catch this kind of problem.

I propose this scenario as something the linter could realise:
Given two goroutines (A and B), and two channels (X and Y)
- X, a `chan bool` signal, is being used to wait for A's completion, but not for B's
- A writes to channel Y, and B reads from channel Y

I believe this always introduces a race condition in both of these situations:
1. If Y is unbuffered, B may or may not complete its last operation
2. If Y is buffered, B could finish any number of operations with A's data

When the 2nd condition occurs, this may be intentional for performance reasons, and perhaps the linter should ignore it.

I think the 1st condition will usually be in error. The linter could suggest to use sync.WaitGroup instead.

**Comment by dominikh** [comment]
golint is concerned with idiomatic code, i.e. style issues. It doesn't check for correctness. As such, detection of race conditions doesn't belong in golint.

On a more general note, detecting race conditions statically is an incredibly hard problem, and tends to have false positive rates of around 50% and worse. Tools that implement such detection tend to require a lot of UX work to make using them bearable. And that's for simple, mutex based synchronisation. Channels merely make the problem harder, because now you need to track channel sizes and how they're passed through the program, plus your usual mutex related checks. Even worse, such detection is concerned with actual data races, not logical races, which certainly can't be easier to detect.

**Comment by KernelDeimos** [comment]
Oh wow, it's that bad? Well at least I gained some insight by posting this - thanks!

**Comment by dominikh** [comment]
https://cseweb.ucsd.edu/~lerner/papers/relay.pdf and http://web.stanford.edu/~engler/racerx-sosp03.pdf are two interesting papers on general static race detection, if I remember correctly.

**Comment by dsnet** [comment]
Closing this since lint is (as Dominik mentioned) primarily about style, not correctness.
