### ISSUE TITLE
exclude vendor dir from matching `...`

### ISSUE THREAD

**Issue by omarkohl** [golang/lint#320]
Go 1.9 changed the behavior of the Go tools such as "go test" and "go vet" to ignore the vendor directory when using triple dot (...) . See golang/go#19090

How about doing the same thing for golint? It makes sense to have different Go tools behave similarly.

**Comment by omarkohl** [comment]
It looks like it is addressed in #303 . Maybe this ticket could be considered as a proposal to make it the default behavior instead of an optional flag.

**Comment by nathany** [comment]
Making the default behaviour to ignore vendor would match Go 1.9, which is preferable in my mind. 

Here are a few reasons for making `golint ./...` ignore the vendor directory by default.

1. Consistent with Go 1.9 behaviour for `go test`, `go list`, etc.
2. As per https://github.com/golang/go/issues/19090, a solution that doesn't rely on Unix-specific tools (xargs) is beneficial for Windows users.
3. When there are an overwhelming number of lint issues from vendor, it's more likely that all lint issues will be ignored, rather than resolving lint issues within the project itself.

For example, in one project I'm working on, it looks like this:

```
❯ golint ./... | wc -l
    3987
```

Many of these lint issues may never be fixed, such as generated code for syscall.

```
vendor/golang.org/x/sys/unix/zsysnum_darwin_amd64.go:364:2: don't use ALL_CAPS in Go names; use CamelCase
...
```

If I break out some console-fu (e.g. StackOverflow) I can limit it to just the project:

```
❯ go list ./... | grep -v /vendor/ | xargs -L1 golint | wc -l
     183
```

But that isn't very user friendly, nor does it work on Windows.

/cc @dsymonds

**Comment by dlsniper** [comment]
Now that Go 1.9+ excludes ` vendor/ ` from ` ./... ` runs, maybe this can be reconsidered? Especially since ` go list ./... | xargs -L1 golint | wc -l ` does not exit with status 1 (unless further bash magic is applied). Thank you.

**Comment by JonasFranzDEV** [comment]
@dlsniper This work for me with go1.10 (including exit code): 
```bash
golint -set_exit_status $(go list ./...)
```

**Comment by yookoala** [comment]
Any updates on the consideration?

**Comment by bfosberry** [comment]
Bump

**Comment by jjrumi** [comment]
Not ideal but `go list ./... | grep -v /vendor/ | xargs -L1 golint -set_exit_status` does exit with error status

**Comment by dlsniper** [comment]
Unfortunately, that's not something that Windows users such as myself can run :(

**Comment by marcusljx** [comment]
Is there any update on this issue? I saw https://github.com/golang/lint/pull/325 but it seems it's been stagnant for over a year... I do have a need to maintain `/vendor` despite using go modules, due to legacy compatibility issues.

**Comment by nathany** [comment]
It looks like work on https://go-review.googlesource.com/c/lint/+/96085 has stalled. Perhaps someone else should pick it up?

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
