### ISSUE TITLE
Linter suggests using reserved words for variable names

### ISSUE THREAD

**Issue by KernelDeimos** [golang/lint#393]
One of the parameters for a function I made is called `type_`, because "type" is a reserved word.

I'm not sure what the convention should be when the name you want to use happens to be a reserved word, but the linter suggests that it should be `type`, which isn't a valid variable name.

**Comment by andybons** [comment]
There will always be instances where the linter falls down and provides a suggestion that can't be implemented.

From what I've seen, `typ` is used in the case where you really want to use `type` but are not able to due to its reserved status.

**Comment by KernelDeimos** [comment]
Posting this in case anyone wants to submit their own solution or fix my PR;

Unfortunately I found out my PR currently has a small error (missing %s in a printf I think - ironically I bet there was a linter warning for that), and I probably won't have time to fix it and test it properly for a while.

**Comment by jucie** [comment]
I submitted a PR that changes slightly the behavior of golint when it removes the underscores from a name to create a valid name. If the suggested new name is a Go keyword, golint no more suggests the replacement, instead it considers the original code valid.

**Comment by patarapolw** [comment]
Still not fixed.

I want to use type; but of course I cannot use it as a variable name. What is a standard solution for this?

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
