### ISSUE TITLE
Warning triggered by //export comments required by --buildmode=c-shared for function export

### ISSUE THREAD

**Issue by franksanders** [golang/lint#408]
golint generates a 'comment on exported function XXX should be of the form "XXX ..."' warning for //export  comments required when using --buildmode=c-shared. Could comments of this form be excluded from the warnings?

**Comment by dominikh** [comment]
You will have to provide an example. golint does have special handling for `//export` comments, but clearly it's not working for your input.

**Comment by franksanders** [comment]
Turns out it's an issue with ordering the comments below is a screen shot of where warnings are and are not generated in case someone else runs into this. Maybe a custom warning when //export is detected but a preceding godoc comment is omitted would be helpful?

![image](https://user-images.githubusercontent.com/4338755/43654532-69ec17fc-9700-11e8-8e5d-ed92e8b43e25.png)

**Comment by sultra** [comment]
@dominikh  I have a same problem ，Can you provide an example what golint doesn't show that warning?

**Comment by vinod023** [comment]
I am also facing same problem. can you help me!

**Comment by l2dy** [comment]
Try using a not-exported function name in Go, see b8599f7d71e7fead76b25aeb919c0e2558672f4a.

**Comment by l2dy** [comment]
> Try using a not-exported function name in Go, see [b8599f7](https://github.com/golang/lint/commit/b8599f7d71e7fead76b25aeb919c0e2558672f4a).

Sorry, please disregard this comment.

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
