### ISSUE TITLE
golint is downloading module dependencies

### ISSUE THREAD

**Issue by defunct73** [golang/lint#437]
OS: `Darwin orion 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`

Go: `go version go1.12 darwin/amd64`

Using Go Modules from outside the GOPATH.

Running golint on a full package path starts downloading files to `~/go/pkg/mod/cache`, e.g.:

```shell
$ ls -ltr ~/go/pkg/mod
ls: /Users/someuser/go/pkg/mod: No such file or directory

(executed from the root of the repo, e.g.: `~/code/bar`)
$ go list -mod=vendor ./... 
$ golint github.com/foo/bar/pkg

$ ls -ltr ~/go/pkg/mod
total 0
drwxr-xr-x  3 someuser  somegroup  96 Feb 28 16:28 cache
```

However, if I run `golint ./...` it doesn't download to the cache, but using `./...` traverses the `vendor` directory, which is undesirable.

**Comment by dmitshur** [comment]
Just checking, but can you try inserting `ls -ltr ~/go/pkg/mod` after the `go list -mod=vendor ./...` command? Could it be that it's `go list` doing that rather than `golint`?

**Comment by jmassara** [comment]
@dmitshur I thought that originally, too and tested it. It _was_ `go list` until I added the `-mod=vendor`.

```sh
$ sudo rm -rf ~/go/pkg/mod
Password:
$ go list -mod=vendor ./...
 ....
$ ls -ltr ~/go/pkg/mod
ls: /Users/someuser/go/pkg/mod: No such file or directory
```

`golint` unfortunately doesn't take build flags.

**Comment by defunct73** [comment]
@dmitshur I thought that originally, too and tested it. It _was_ `golist` until I added the `-mod=vendor` flag.

```shell
$ sudo rm -rf ~/go/pkg/mod
Password:
$ go list -mod=vendor ./...
 ....
$ ls -ltr ~/go/pkg/mod
ls: /Users/someuser/go/pkg/mod: No such file or directory
```

`golint` unfortunately doesn't take build flags.

**Comment by superstas** [comment]
Hi there, we've experienced the same issue. Do you have any update on it?

**Comment by steve-offutt** [comment]
I was experiencing this today as well. I found something that worked for me.
```
golint $(go list -mod=vendor -f '{{ .Dir }}' ./...)
```

Here we are instructing the `go list` command to format the packages contained in our module with directory names instead of the _package_ name. I quickly looked at the source for `golint` and maybe this is attempting to download the deps: https://github.com/golang/lint/blob/83fdc39ff7b56453e3793356bcff3070b9b96445/golint/golint.go#L133. Since `golint` (correctly) sees the output from `go list` as a package we need to format as a directory to prevent golint building the package with deps.

Hope this helps someone!

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
