### ISSUE TITLE
Add warning for code which depends on unspecified evaluation order

### ISSUE THREAD

**Issue by zhishi** [golang/lint#443]
Recently I see some production code with below pattern:
.....
    return b, update(&b)
}
The real production code use a function closure which directly modify b without pointer, but I think the order issue is same. It's very similar to the usual return multiple values style in go. But it depends on a not specified behavior which has risk to change in future and very hard to debug. 

based on golang spec, the evaluation order of first b and the func call of update(&b) is unspecified, and the result shows current golang implementation will execute all the func calls before the evaluation of other expressions. I also confirmed it by testing below code:

func change(v *int) bool {
    *v = 3
    return true
}

func value(v int) int {   
    return v 
}

func main() {
    b := 1
    fmt.Println(b + 1, value(b + 1), change(&b))
}

Output:
4 2 true 

I think it's better to show some warnings (or written into spec which make sure it won't change in future). Is it possible to add the check in golint: when a comma separated expression (including return, assignment, func parameters etc) contains variable who is also referenced in a func closure (or get pointer in a func parameter) in the same expression, shows a warning say the execution order is unspecified may cause bug?

**Comment by randall77** [comment]
Just passing the pointer is not enough - we have to know that the pointer is written to. If the function only reads the pointer, that's ok.
So we'd need to look inside the function being called. That's possible to do statically in some cases, but certainly not all.

We don't want to write whole-program analysis into the spec. It's possible to put such a check in vet, but it's going to be a lot of work and will only catch some cases.

**Comment by zhishi** [comment]
Thanks for response!

Yes I agree it’s hard to check all the cases, but my understanding lint
only give suggestions and not intent to be perfect, the purpose of it is to
prevent people from writing confusing or buggy code style. I think that
coding style should be avoided even it works fine.

Actually my personal opinion is define the evaluation order more clearly in
spec, because comma separated expression is used a lot in go, why not make
it predictable like other language (I mean c or c++)?

Keith Randall <notifications@github.com>于2019年3月16日 周六下午12:13写道：

**Comment by randall77** [comment]
> why not make it predictable like other language (I mean c or c++)?

Evaluation order is not predictable in c or c++.
https://en.cppreference.com/w/cpp/language/eval_order

**Comment by zhishi** [comment]
I see, guess there is no perfect solution for such problem. So it’s still
depends on best practice from people, which is the reason I hope lint could
help as much as possible, but as you said, it’s too hard to cover all the
cases.

Thanks.

Keith Randall <notifications@github.com>于2019年3月16日 周六下午1:52写道：

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
