### ISSUE TITLE
Migrate to x/analysis 

### ISSUE THREAD

**Issue by kravtsov-dima** [golang/lint#463]
Hey
What do you think about migrating to [golang.org/x/tools/go/analysis](https://godoc.org/golang.org/x/tools/go/analysis) compatible syntax?

Or, we can create a method that works with *ast.File. Then outside I can implement the logic of x/analysis Analyzer. 

What do you think about it?

**Comment by slon** [comment]
@alandonovan would you please help us with this question?

I'm not sure who is the current maintainer of https://github.com/golang/lint. Since you are involved with x/analysis and helped me with other issue, you might know about current plans.

**Comment by ianthehat** [comment]
Lint should be migrated to use the go/analysis package for certain.
it will probably be @matloob that owns doing this, some of the checkers have basically already been written by Dominik in static check anyway, but contributions along those lines would also be welcome.

**Comment by alandonovan** [comment]
I neither own nor use golint, so I'm not the best person to decide, but my understanding of golint is that it works (essentially) on the text or parse tree of a single file at a time. I suggest you move any type-based analysis into the go/analysis framework and let golint's domain be superficial file-at-a-time checks.

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
