### ISSUE TITLE
Can golint works with goland plugin File Watchers more friendly?

### ISSUE THREAD

**Issue by asurasoft** [golang/lint#482]
I added golint to goland's "on save action", but when saved(after file modified), no tips found.

I must select "Always" on choice "show console" In Advanced Options. So it can work normal.

I found that golint command always exit with status 0. 

can it return with status 1 when errors checked or need i pass more config params to run golint cmd?

**Comment by pseidemann** [comment]
you can use `golint -set_exit_status`

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
