### ISSUE TITLE
Reopen issue #89

### ISSUE THREAD

**Issue by jossef** [golang/lint#491]
Reopen issue #89
You shouldn't ignore your users' feedback.

![image](https://user-images.githubusercontent.com/1287098/81019153-b99f6800-8e6e-11ea-850e-5196020d9a0d.png)

@tklauser @tzneal @vcabbage @vstefanovic @wathiede @williamweixiao @ysmolsky @katiehockman @LMMilewski @marete @martisch @mattn @mdempsky @mdlayher @minux @mpvl @mundaym @mvdan @myitcv @namusyaka @neelance @nicolasgarnier @odeke @oiooj @paulzhol @peterbourgon @prattmic @rakyll @rasky @rui314 @SamWhited @sbinet @sdboyer @shawnps @smasher164 @thanm

**Comment by jossef** [comment]
@titanous @0intro @4ad @aclements @alexbrainman @ality @ALTree @andybons @artyom @bcmills @benshi001 @broady @c4milo @cflewis @davidlazar @dmitshur @dominikh @dskinner @dsnet @dsymonds @dvyukov @eliben @evandbrown @fatih @FiloSottile @gbbr @HaraldNordgren @jimmyfrasche @johanbrandhorst @josephlr @jpoirier

**Comment by noonien** [comment]
I strongly suggest you ask for a refund!

**Comment by mdlayher** [comment]
Please don't spam mentions in the future.

**Comment by ianlancetaylor** [comment]
Thanks, but, quoting the original response:

> When code can't follow the usual style conventions there's nothing to do. Just ignore what golint says. Its output is meant for humans anyway.

The lint program implements a certain set of style guidelines, that are now documented at https://golang.org/wiki/CodeReviewComments.  If you want to follow a different set of style guidelines, modify or rewrite golint.

The golint program is not intended to be all things to all people.

**Comment by as** [comment]
I too can send a link to 31 people but that isn't a representative sample of users' opinions, nor is it a meritable argument on its own to take any action. 

Ignoring something and acknowledging it but not doing anything are different things. They should not be equivocated.

**Comment by lane-c-wagner** [comment]
God please don't make golint like eslint. Keep the rules consistent. Down with configurability.

**Comment by jossef** [comment]
You can keep telling yourself that. It's not what most users want judging by the vote count on #263, #186, ...

![image](https://user-images.githubusercontent.com/1287098/81090945-2ebe7c00-8f07-11ea-8d07-30f748e1b516.png)

**Comment by cflewis** [comment]
[golangci-lint](https://github.com/golangci/golangci-lint) allows you to exclude certain messages, and supports golint. The license is permissive. I suggest you consider switching your tool chain to use that instead.

As @ianlancetaylor said, it is not possible to make tools that are all things to all people, and those that attempt it invariably end up too complex. I don’t want to put words in anyone’s mouth, but reducing complexity in the tooling has generally worked well for the Go project and I wouldn’t expect that to change.

I think you will be happier in the long run if you try to respect that the this issue is closed, and move on to golangci-lint which is a solution that is available to you immediately.

**Comment by chavacava** [comment]
[`revive`](https://github.com/mgechev/revive) is a drop-in replacement for `golint` that allows disabling certain messages by configuration and is extensible (it supports +50 checking rules)
