### ISSUE TITLE
zsh: command not found: golint

### ISSUE THREAD

**Issue by serenaxiong12** [golang/lint#494]
When I run _go list -f {{.Target}} golang.org/x/lint/golint_ it says that i have golint install in go/bin and I added it to my .bashrc file like this: _export PATH=$PATH:$GOPATH/bin/golint_

But I am still getting a command not found error, any ideas as to why this might be happening?

**Comment by d3an** [comment]
I did the same thing, but with a zsh-configured terminal. When I echo the PATH variable it lists the golint target, but still won't execute. I can run the golint executable from the directory it was installed to, but it is still not accessible by running `$ golint`. Any help would be appreciated.

**Comment by HundredBillion** [comment]
I am also having this issue on an M1 macbook pro. However @d3an's solution did not help.
I removed PATH variables in `.zprofile` and added them to `.zshrc` and I still get this error

```export GOPATH=$HOME/golang
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export CGO_ENABLED=1; export CC=gcc;
export PATH=$PATH:/Users/david.lee/golang/bin/golint
export GO111MODULE=on```


Any ideas?

**Comment by bakeruk** [comment]
Double-check that your `go env` values match your `.bashrc` or `.zshrc` exports.

```zsh
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export GOROOT=/usr/local/Cellar/go/1.15.7_1/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
```

Also, don't forget to reload your `.bashrc` or `.zshrc` settings.

```zsh
# Bash
source ~/.bashrc

# zsh
exec zsh
```

See if you can find the package in your `$GOPATH/bin` directory. If it exists, there might be an issue with your `PATH` exports. Try commenting out each `export` line and reload the settings `.bashrc` or `.zshrc` settings - rinse and repeat. Keep it simple and try copying mine (above) and update the values to be your own.

**Comment by meerasndr** [comment]
Thanks @bakeruk, this helped solve the issue for me.

**Comment by KeyHui** [comment]
Thanks, @bakeruk. Your solution is work for me.

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
