### ISSUE TITLE
    module declares its path as: golang.org/x/lint                 but was required as: github.com/golang/lint

### ISSUE THREAD

**Issue by tousif12** [golang/lint#508]
I was having this issue:

```
go get: github.com/golang/lint@v0.0.0-20201208152925-83fdc39ff7b5: parsing go.mod:
        module declares its path as: golang.org/x/lint
                but was required as: github.com/golang/lint
```

**and applied a workaround fix after reading so many closed issues on github regarding `golang/lint`** 

fix is   `go mod edit -replace github.com/golang/lint=golang.org/x/lint@latest`

**Now After applying this Fix I am getting this issue** 

`go: golang.org/x/lint@v0.0.0-20201208152925-83fdc39ff7b5 used for two different module paths (github.com/golang/lint and golang.org/x/lint)`

**My Go version :**
`   go version go1.14 linux/amd64`

**and my go.mod file is**  

```
module gitlab.com/proj-ride/proj-src/services/event

go 1.14

require (
	github.com/golang/protobuf v1.4.3
	github.com/google/go-cmp v0.5.4 // indirect
	golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 // indirect
	google.golang.org/protobuf v1.25.0
)

replace github.com/golang/lint => golang.org/x/lint v0.0.0-20201208152925-83fdc39ff7b5

```

**Comment by mvdan** [comment]
Thank you for submitting this issue! As per https://github.com/golang/go/issues/38968, we are freezing and deprecating golint. There's no drop-in replacement to golint per se, but you should find that [Staticcheck](https://staticcheck.io/) works well in encouraging good Go code, much like golint did in the past, since it also includes style checks. There's always `gofmt` and `go vet` too, of course.

If you would like to contribute further, I'd encourage you to engage [Staticcheck's issue tracker](https://github.com/dominikh/go-tools/issues) or look at [vet's open issues](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+cmd%2Fvet+in%3Atitle), as they are both actively maintained. If you have an idea that doesn't fit into either of those tools, you could look at [other Go linters](https://github.com/golangci/awesome-go-linters), or write your own - these days it's fairly straightforward with [go/analysis](https://pkg.go.dev/golang.org/x/tools/go/analysis).

To help avoid confusion, I'm closing all issues before we freeze the repository. If you have any feedback, you can leave a comment on the proposal thread where it was decided to deprecate golint - though note that the proposal has been accepted for nearly a year. Thanks!
