### ISSUE TITLE
blacklist of files

### ISSUE THREAD

**Issue by drewwells** [golang/lint#98]
There's currently no way to exclude certain files from linting rules ie. lint `a.go` `b.go`, but skip `c.go`.

I tried getting around this by using `go list`, only to find that `golint pkgA/file pkgB/file` throws errors about mismatched packages. A filter similar to `go test -run` would very helpful for transitioning to the use of golint.

**Comment by dsymonds** [comment]
Just use grep to filter the output if that's what you want. Golint does not force you to address every thing it flags (there will be false positives).

**Comment by drewwells** [comment]
Grep will always return exit 0. Is golint always going to return 0?

**Comment by dsymonds** [comment]
Most likely, though it's trivial enough to run (golint ... || true) to make sure.

**Comment by drewwells** [comment]
We'd like our CI to fail on linting errors, grep masks that.

**Comment by dsymonds** [comment]
That's not what golint is for. It does not produce errors, only
suggestions. Please read the README.

**Comment by zimmski** [comment]
@drewwells: Static analysis tools like golint always produce suggestions. There can be a lot of false positives in there and there is often no way to flag them. However, I too like my CI to fail because I often forget to run all tools myself. You can have a look at the linting section here https://github.com/zimmski/tavor/blob/master/.travis.yml to get an idea on how you can accomplish the same.

**Comment by drewwells** [comment]
That's a good idea, thanks! We can whitelist lint suggestions that we
definitely want to fail on.
